server:
  port: 8000

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.hr_manage.pojo

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hr_manage?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 258520



#showSql
logging:
  level:
    com:
      hr_manage:
        mapper: debug


# 自定义的jwt配置
jwt:
  # 过期时间：24小时
  expire: 86400000
  # 密钥
  secret: 6Dx8SIuaHXJYnpsG18SSpjPs50lZcT52




filePath: https://localhost:8000/public/




